### ISSUE TITLE
in place operation problem

### ISSUE THREAD

**Issue by as595** [halahup/NeuralStyleTransfer#1]
Hi, when I run the code I get this error: 

"RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.FloatTensor [1, 3, 512, 512]] is at version 3; expected version 0 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!"

The trace looks like it's a problem in: line 35, in get_style_activations
    features = [self.vgg[:4](x)] + [self.vgg[:7](x)] + [self.vgg[:12](x)] + [self.vgg[:21](x)] + [self.vgg[:30](x)]

Any ideas?

full trace below:

python3 nst.py 
Iteration: 0, Content Loss: 414.771, Style Loss: 3915665.448, Var Loss: 22576.537
../torch/csrc/autograd/python_anomaly_mode.cpp:57: UserWarning: Traceback of forward call that caused the error:
  File "nst.py", line 174, in <module>
    save_every=save_every)
  File "nst.py", line 100, in main
    noise_style_activations = vgg.get_style_activations(noise)
  File "/Users/as595/SRC/GITHUB/NeuralStyleTransfer/vgg.py", line 35, in get_style_activations
    features = [self.vgg[:4](x)] + [self.vgg[:7](x)] + [self.vgg[:12](x)] + [self.vgg[:21](x)] + [self.vgg[:30](x)]
  File "/Users/as595/SRC/GITHUB/p3env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/as595/SRC/GITHUB/p3env/lib/python3.6/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/Users/as595/SRC/GITHUB/p3env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/as595/SRC/GITHUB/p3env/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 343, in forward
    return self.conv2d_forward(input, self.weight)
  File "/Users/as595/SRC/GITHUB/p3env/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 340, in conv2d_forward
    self.padding, self.dilation, self.groups)

Traceback (most recent call last):
  File "nst.py", line 174, in <module>
    save_every=save_every)
  File "nst.py", line 141, in main
    total_loss.backward()
  File "/Users/as595/SRC/GITHUB/p3env/lib/python3.6/site-packages/torch/tensor.py", line 118, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/Users/as595/SRC/GITHUB/p3env/lib/python3.6/site-packages/torch/autograd/__init__.py", line 93, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.FloatTensor [1, 3, 512, 512]] is at version 3; expected version 0 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!

(I've hard coded the image paths:
style_img_path = "./style_img_1.jpeg"
content_img_path = "./content_img_1.jpg"   
)

**Comment by sykhan88** [comment]
Hi, got the same issue as above. Any resolution to this? Just running the following:
```
python nst.py --style_img style_img_1.jpeg --content_img content_img_1.jpg 
``` 
and getting the inplace operation error. the trackback is as follows:
```
Iteration: 0, Content Loss: 416.485, Style Loss: 3939776.719, Var Loss: 22612.062
Traceback (most recent call last):
  File "nst.py", line 178, in <module>
    save_every=save_every)
  File "nst.py", line 149, in main
    total_loss.backward()
  File "/Users/sk/anaconda3/envs/nst/lib/python3.6/site-packages/torch/tensor.py", line 102, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/Users/sk/anaconda3/envs/nst/lib/python3.6/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation
```
